name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            cuda: "12.5.0"

    env:
      config: "Release"

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libhwloc-dev

      - name: Install CUDA
        uses: pkestene/cuda-toolkit@fix/cuda-keyring-version
        id: cuda-toolkit
        if: runner.os == 'Linux'
        with:
          sub-packages: '["nvcc", "nvrtc", "cudart"]'
          cuda: ${{ matrix.cuda }}
          method: network
          use-github-cache: true

      - name: nvcc check
        shell: bash
        run: |
          nvcc -V
          ls "$CUDA_PATH"
          ls "$CUDA_PATH/bin"
          ls "$CUDA_PATH/include"

      - name: cmake version
        shell: bash
        run: cmake --version

      # make sure to explicitly checkout git submodule !
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: configure_openmp
        run: mkdir build_openmp && cd build_openmp && cmake -DEULER_KOKKOS_BUILD_KOKKOS=ON -DEULER_KOKKOS_BACKEND=OpenMP ..

      - name: make_openmp
        run: cd build_openmp && make

      - name: configure_cuda
        run: mkdir build_cuda && cd build_cuda && cmake -DEULER_KOKKOS_BUILD_KOKKOS=ON -DEULER_KOKKOS_BACKEND=Cuda -DKokkos_ARCH_AMPERE80=ON ..

      - name: make_cuda
        run: cd build_cuda && make
